AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  ApiGatewayApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: Dev
    Variables:
      LambdaFunctionName: !Ref TimeFunction
      RestApiId: !Ref ApiGatewayApi
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Environment:
        Variables:
          TIME_ZONE: !Ref timeZoneParam
          STAGE: !Ref stage
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /TimeResource
            Method: GET
Parameters:
  timeZoneParam:
    Type: String
  stage:
    Type: String
